# Generated by Django 6.0.1 on 2026-03-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_type', models.CharField(choices=[('LPG', 'LPG'), ('COOKING', 'Cooking Gas'), ('SMOKE', 'Smoke'), ('PROPANE', 'Propane'), ('METHANE', 'Methane'), ('HYDROGEN', 'Hydrogen'), ('ALCOHOL', 'Alcohol'), ('CO', 'Carbon Monoxide')], max_length=20)),
                ('value', models.FloatField()),
                ('is_safe', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
