# Generated by Django 6.0.1 on 2026-03-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasreading',
            name='gas_type',
            field=models.CharField(default='COMBUSTIBLE_GAS', max_length=20),
        ),
    ]
